// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    // Migrations run against the direct (non-pooled) connection when available.
    // Poolers like Neon's pgbouncer can reject some DDL statements.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
